#@TYPE: Machine
#@NAME: Generic riscv64 CHERI machine
#@DESCRIPTION: Machine configuration for running a generic riscv64 CHERI

require conf/machine/include/riscv/qemuriscvcheri.inc

DEFAULTTUNE:cheri = "riscv64cheri"

XVISOR_PLAT = "riscv/virt64"

EXTRA_IMAGEDEPENDS += "u-boot-cheri"
UBOOT_MACHINE = "qemu-riscv64_cheri_purecap_smode_defconfig"
UBOOT_ELF = "u-boot"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "kernel-module-rtc-goldfish"
