DISTRO = "cheri"
DISTRO_NAME = "CHERI enabled distro for debugging"
DISTRO_VERSION = "1.0"

# TO-DO add maintainers and their emails
MAINTAINER = "Codasip < ??>"

INIT_MANAGER = "sysvinit"
VIRTUAL-RUNTIME_dev_manager = "busybox-mdev"

EXTRA_IMAGE_FEATURES += "debug-tweaks"

LLVMVERSION = "19.0.0"
